### ISSUE TITLE
Add end-to-end tests into CI execution

### ISSUE THREAD

**Issue by hectorgomezv** [5afe/safe-client-gateway-nest#128]
In order to have a greater test coverage and detect defects on development time, it would be very useful to implement an end to end tests suite into the CI pipeline.

### Requirements
- A fresh Redis instance should be created/destroyed during the CI execution. 
- Some environment variables should be set in the CI environment, so Github Secrets could be used.

### Decision points
- This service uses both Safe Transaction Service and Safe Config Service as data providers. Which environment should be used by the end to end tests? Production?
- Related to the previous question: which chain(s) should be used? Goerli? Mainnet?
- Also related: should we test side-effect (post, put, delete, etc.) endpoints just for Goerli and non-side-effect ones (get) for several networks including Mainnet?

Please comment 🙂 @fmrsabino @Uxio0 @moisses89

**Comment by Uxio0** [comment]
This sounds really good to me

> A fresh Redis instance should be created/destroyed during the CI execution.

I think it's a red flag that we currently don't test redis integration at all. Having Redis mocked all the time can lead to bugs when the application is deployed.

 > This service uses both Safe Transaction Service and Safe Config Service as data providers. Which environment should be used by the end to end tests? Production?

We can start with staging and reevaluate if we see problems.

> Related to the previous question: which chain(s) should be used? Goerli? Mainnet?

I would target Goerli first unless there's something that cannot be tested (I cannot think of any case now)

> Also related: should we test side-effect (post, put, delete, etc.) endpoints just for Goerli and non-side-effect ones (get) for several networks including Mainnet?

I would currently target all tests for Goerli, unless there's a good reason for some endpoint to test another network (for example, to see caching invalidation correctly working for multiple networks)

**Comment by fmrsabino** [comment]
> This sounds really good to me
> 
> > A fresh Redis instance should be created/destroyed during the CI execution.
> 
> I think it's a red flag that we currently don't test redis integration at all. Having Redis mocked all the time can lead to bugs when the application is deployed.

This project is in early stages and caching was also done recently. I wouldn't call it a red flag at this stage. Testing Redis means testing integration which is something that we are considering now.

> > This service uses both Safe Transaction Service and Safe Config Service as data providers. Which environment should be used by the end to end tests? Production?
> 
> We can start with staging and reevaluate if we see problems.

I would focus on `staging`. One of the main reasons is that we see features changed more often there. If something is not working we would get a warning earlier in the process. However this raises the question if e2e tests should be required to pass in a normal development process or just on a release/pre-release stage.

> > Related to the previous question: which chain(s) should be used? Goerli? Mainnet?
> 
> I would target Goerli first unless there's something that cannot be tested (I cannot think of any case now)

I agree 👍 

> > Also related: should we test side-effect (post, put, delete, etc.) endpoints just for Goerli and non-side-effect ones (get) for several networks including Mainnet?
> 
> I would currently target all tests for Goerli, unless there's a good reason for some endpoint to test another network (for example, to see caching invalidation correctly working for multiple networks)

I would start simple with this one. Let's focus on Goerli for now.
