### ISSUE TITLE
Add collectibles V1

### ISSUE THREAD

**Issue by moisses89** [5afe/safe-client-gateway-nest#136]
- Add `/v1/chains/<chain_id>/safes/<safe_address>/collectibles?<trusted>&<exclude_spam>` route
- Caching support should be added
- Tests should be added
- OpenApi specification should be added

**Comment by fmrsabino** [comment]
Let's not focus on this one right now since v2 should be used instead by the clients. We can come back to this one later if there are more dependencies.

**Comment by hectorgomezv** [comment]
@fmrsabino @moisses89 @Uxio0 I'm closing this issue since the the collectibles v1 endpoint is not available anymore in the Transaction Service (deleted in https://github.com/safe-global/safe-transaction-service/pull/1361)
