### ISSUE TITLE
Add GET /transactions/{details_id} route

### ISSUE THREAD

**Issue by fmrsabino** [5afe/safe-client-gateway-nest#154]
Safe Transaction Service dependencies:
- [x] `/v1/safes/{}/transfers/` https://github.com/5afe/safe-client-gateway-nest/issues/125
- [x] `/v1/safes/{}/module-transactions/` https://github.com/5afe/safe-client-gateway-nest/issues/163
- [x] `/v1/multisig-transactions/{}/` https://github.com/5afe/safe-client-gateway-nest/issues/164
- [x] `/v1/safes/{}/` https://github.com/5afe/safe-client-gateway-nest/pull/116
- [x] `/v1/tokens/` https://github.com/5afe/safe-client-gateway-nest/issues/166
- [x] `/v1/contracts/{}/` https://github.com/5afe/safe-client-gateway-nest/issues/100

**Comment by hectorgomezv** [comment]
@fmrsabino is this duplicated by https://github.com/5afe/safe-client-gateway-nest/issues/262? Should we close one of them?

**Comment by fmrsabino** [comment]
> @fmrsabino is this duplicated by #262? Should we close one of them?

I will close this one since https://github.com/5afe/safe-client-gateway-nest/issues/262 is more up to date. Thanks!
