### ISSUE TITLE
Map Safe Apps "origin" field for Multisig Transactions

### ISSUE THREAD

**Issue by hectorgomezv** [5afe/safe-client-gateway-nest#201]
Safe Apps `origin` field should be mapped when retrieving multisig transactions. This work is extracted from #197. It seems [the Rust implementation](https://github.com/safe-global/safe-client-gateway/blob/main/src/routes/transactions/converters/safe_app_info.rs) contains special logic to map this field, so it deserves some special attention.

**Comment by hectorgomezv** [comment]
Blocked by #159

**Comment by moisses89** [comment]
@hectorgomezv is this still blocked?

**Comment by hectorgomezv** [comment]
> @hectorgomezv is this still blocked?

Not anymore, I removed the tag, thanks!
