### ISSUE TITLE
Use an automatic fake data generator on tests

### ISSUE THREAD

**Issue by hectorgomezv** [5afe/safe-client-gateway-nest#24]
**Summary**
Currently we are generating our test data manually per test. It would be nice to integrate a tool to generate this fake data to favor tests robustness. [Faker](https://www.npmjs.com/package/@faker-js/faker) seems a good candidate for this.

**Acceptance criteria**
- An automatic tool should be added as development-time dependency only.
- Current and further test classes should use this tool instead of manually generate test/fake data.

**Comment by fmrsabino** [comment]
Tracking under #31 for now
